import Navbar from '@/components/Navbar';
import './globals.css';
import MyProfilePic from '@/components/MyProfilePic';

export const metadata = {
  title: 'Next Markdown Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-slate-800">
        <Navbar />
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}
